/* You are given an array people where people[i] is the weight of the ith person, and an infinite number of boats where each boat can carry a maximum weight of limit...
Each boat carries at most two people at the same time, provided the sum of the weight of those people is at most limit...
Return the minimum number of boats to carry every given person...
* Eg 1: people = [1, 2]               limit = 3                          Boats = 1
* Eg 2: people = [3, 2, 2, 1]         limit = 3                          Boats = 3
* Eg 3: people = [3, 5, 3, 4]         limit = 5                          Boats = 3
* Eg 4: people = [2]                  limit = 4                          Boats = 1
 */
import java.util.*;
public class Boat 
{
    public int RescueBoats(Vector<Integer> people, int limit)
    {
        Collections.sort(people);    // Sorting the array on the basis of the people weights...
        int j = 0, count = 0;         // Counter variables...
        if(people.size() >= 2)
        {
            while(people.get(j) + people.get(j + 1) <= limit)      // If two persons can be carried on a single boat...
            {
                people.remove(j);     // Remove the first person...
                people.remove(j);     // Remove the next person in the vector...
                count++;
            }
            while(j < people.size())    // While the vector is not empty...
            {
                people.remove(j);    // Now one person will be carried per boat...
                count++;
            }
        }
        else
            return 1;     // If there is a single person, then in any case we need only one boat...
        return count;     // Returning the count variable...
    }
    public static void main(String[] args)
    {
        Scanner sc = new Scanner(System.in);
        int x, a;
        System.out.print("Enter the number of people : ");
        x = sc.nextInt();
        Vector<Integer> people = new Vector<Integer>();     // Integer vector created...
        for(int i = 0; i < x; i++)
        {
            System.out.print("Enter "+(i+1)+" th Person weight : ");
            a = sc.nextInt();     // User Input...
            people.add(i, a);     // Adding the value...
        }
        System.out.print("Enter the weight limit a boat can carry : ");
        x = sc.nextInt();
        Boat boat = new Boat();       // Object creation...
        a = boat.RescueBoats(people, x);      // Function calling...
        sc.close();
    }
}

// Time Complexity  - O(n log n) time...
// Space Complexity - O(n) space...